language: r
script: true

jobs:
  include:
  - stage: test
    r: devel
  - stage: full
    r: release
    env:
    - BUILD_PKGDOWN=true
  - os: osx
    r: release
    env:
      - BUILD_PKGDOWN=true
  - r: 3.5
  - r: 3.4
  - r: 3.3
  - r: 3.2
